name: Deploy Node.js Backend with Apache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload backend files
        run: |
          rsync -avz --delete \
            -e "ssh -p 22022 -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/html/somesh/Temp-humidiy-logger-api \
            --exclude='.git' --exclude='.github' --exclude='node_modules'

      - name: Debug deployment
        run: |
          ssh -tt -p 22022 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            echo "==> WHOAMI:"
            whoami

            echo "==> ENV:"
            env

            echo "==> Check if NVM exists"
            ls -l $HOME/.nvm/nvm.sh || echo "NVM not found!"

            echo "==> Source NVM and use Node"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18
            nvm use 18
            node -v
            npm -v

            echo "==> Go to API directory"
            cd /var/www/html/somesh/Temp-humidiy-logger-api
            ls -lah

            echo "==> Run npm install"
            npm install

            echo "==> Start PM2"
            npx pm2 restart ecosystem.config.js || npx pm2 start ecosystem.config.js
            npx pm2 save
            EOF
